[package]
name = "wasip2-example"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "wasip2_example"
path = "src/main.rs"

[lints]
workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = "0.3"
jevrs = { path = "../../crates/jevrs", version = "0.1.0", default-features = false, features = [
  "derive",
  "wasip2",
] }
