[package]
name = "jevrs-derive"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
jevrs = { path = "../jevrs", default-features = false }
jevrs-core = { path = "../jevrs-core" }
trybuild = "1"
